export const propertyApiData = {
    "data": [{
        "property_id": 19,
        "title": "Luxury 3BHK Apartment",
        "description": "Spacious apartment with modern amenities",
        "location": "Mumbai",
         "bhk": 3,
         "property_type": "Apartment",
        "construction_type": "New",
         "construction_status": "Ready to Move",
        "price": "7500000.00",
        "area_sqft": 1500, "verified": 1,
        "owner_id": 1,
        "created_at": "2026-03-11T11:49:33.000Z",
        "latitude": null,
        "longitude": null,
        "image": null
    },

    {
        "property_id": 20, "title": "Cozy 2BHK Villa",
        "description": "Beautiful villa with garden",
        "location": "Pune", "bhk": 2,
        "property_type": "Villa",
        "construction_type": "Resale",
        "construction_status": "Ready to Move",
        "price": "5500000.00", "area_sqft": 1200,
        "verified": 1, "owner_id": 1,
        "created_at": "2026-03-11T11:49:33.000Z",
        "latitude": null,
        "longitude": null,
        "image": null
    },
    {
        "property_id": 21,
        "title": "3BHK Under Construction Apartment",
        "description": "New apartment under construction",
        "location": "Bangalore",
        "bhk": 3,
        "property_type": "Apartment", "construction_type": "New", "construction_status": "Under Construction",
        "price": "6500000.00", "area_sqft": 1400,
         "verified": 0, 
         "owner_id": 1,
          "created_at": "2026-03-11T11:49:33.000Z",
           "latitude": null, 
           "longitude": null,
            "image": null
    }, {
        "property_id": 22, "title": "4BHK Luxury Villa",
        "description": "Spacious villa with private pool",
        "location": "Hyderabad", "bhk": 4,
         "property_type": "Villa",
        "construction_type": "New", "construction_status": "Ready to Move",
        "price": "12500000.00", "area_sqft": 2500, "verified": 1, "owner_id": 1,
        "created_at": "2026-03-11T11:49:33.000Z", "latitude": null, "longitude": null,
        "image": null
    }, {
        "property_id": 23,
        "title": "1BHK Studio Apartment",
        "description": "Compact studio ideal for singles",
        "location": "Mumbai",
        "bhk": 1, "property_type": "Apartment",
        "construction_type": "Resale",
        "construction_status": "Ready to Move",
        "price": "3500000.00",
        "area_sqft": 500, "verified": 1,
        "owner_id": 1,
        "created_at": "2026-03-11T11:49:33.000Z",
        "latitude": null,
        "longitude": null,
        "image": null
    },
    {
        "property_id": 24,
        "title": "2BHK Apartment with Balcony",
        "description": "Apartment with spacious balcony",
        "location": "Chennai", "bhk": 2,
        "property_type": "Apartment",
        "construction_type": "New",
        "construction_status": "Ready to Move",
        "price": "4800000.00", "area_sqft": 1100,
        "verified": 1, "owner_id": 1,
        "created_at": "2026-03-11T11:49:33.000Z",
        "latitude": null,
        "longitude": null,
        "image": null
    }, {
        "property_id": 25,
        "title": "5BHK Penthouse",
        "description": "Top floor penthouse with city view",
        "location": "Delhi", "bhk": 5,
        "property_type": "Apartment",
        "construction_type": "New",
        "construction_status": "Under Construction",
        "price": "20000000.00", "area_sqft": 3200,
        "verified": 0, "owner_id": 1,
        "created_at": "2026-03-11T11:49:33.000Z",
        "latitude": null,
        "longitude": null,
        "image": null
    }, {
        "property_id": 26,
        "title": "3BHK Villa with Garden",
        "description": "Villa with landscaped garden",
        "location": "Pune", "bhk": 3,
        "property_type": "Villa",
        "construction_type": "New",
        "construction_status": "Ready to Move",
        "price": "9000000.00",
        "area_sqft": 1800,
        "verified": 1, "owner_id": 1,
        "created_at": "2026-03-11T11:49:33.000Z",
        "latitude": null,
        "longitude": null,
        "image": null
    },
    {
        "property_id": 27, "title": "2BHK Affordable Apartment",
        "description": "Budget-friendly apartment",
        "location": "Bangalore",
        "bhk": 2,
        "property_type": "Apartment",
        "construction_type": "Resale",
        "construction_status": "Ready to Move",
        "price": "4200000.00",
        "area_sqft": 1000,
        "verified": 1, "owner_id": 1,
        "created_at": "2026-03-11T11:49:33.000Z",
        "latitude": null,
        "longitude": null, "image": null
    },
    {
        "property_id": 28,
        "title": "4BHK Luxury Apartment",
        "description": "High-end apartment with gym and pool",
        "location": "Mumbai", "bhk": 4,
        "property_type": "Apartment",
        "construction_type": "New",
        "construction_status": "Under Construction",
        "price": "15000000.00",
        "area_sqft": 2200,
        "verified": 0, "owner_id": 1,
        "created_at": "2026-03-11T11:49:33.000Z",
        "latitude": null,
        "longitude": null,
        "image": null
    },
    {
        "property_id": 29, "title": "qweerr",
        "description": "awsome",
        "location": "jaipur",
        "bhk": 3, "property_type": "Apartment",
        "construction_type": "New",
        "construction_status": "Ready to Move",
        "price": "1234456.00",
        "area_sqft": 1233, "verified": 1,
        "owner_id": null,
        "created_at": "2026-03-11T13:18:47.000Z",
        "latitude": "26.8934430",
        "longitude": "75.8357040",
        "image": null
    },
    {
        "property_id": 30,
        "title": "Harish",
        "description": "qwerty",
        "location": "jaipur",
        "bhk": 3,
        "property_type": "Apartment",
        "construction_type": "New",
        "construction_status": "Ready to Move",
        "price": "12234556.00",
        "area_sqft": 234,
        "verified": 1, "owner_id": null,
        "created_at": "2026-03-11T13:26:51.000Z",
        "latitude": "24.0000000",
        "longitude": "75.0000000",
        "image": null
    }]
}
